// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDq7npug1uu1odaLn92ZZnnYdIM3tVJ2c',
    appId: '1:234998723188:web:413ff423db11799ae79721',
    messagingSenderId: '234998723188',
    projectId: 'tangsugar-24bd1',
    authDomain: 'tangsugar-24bd1.firebaseapp.com',
    databaseURL: 'https://tangsugar-24bd1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tangsugar-24bd1.appspot.com',
    measurementId: 'G-PZF9FNE9FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPPtVfldEshBC6MrH96RZbswMo9u70vuE',
    appId: '1:234998723188:android:fdb564a0db9f86cfe79721',
    messagingSenderId: '234998723188',
    projectId: 'tangsugar-24bd1',
    databaseURL: 'https://tangsugar-24bd1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tangsugar-24bd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXqFqmbusOjlCJvlasM-by6vMUjDiexTk',
    appId: '1:234998723188:ios:55f76daecd571269e79721',
    messagingSenderId: '234998723188',
    projectId: 'tangsugar-24bd1',
    databaseURL: 'https://tangsugar-24bd1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tangsugar-24bd1.appspot.com',
    iosBundleId: 'com.example.tangsugar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXqFqmbusOjlCJvlasM-by6vMUjDiexTk',
    appId: '1:234998723188:ios:55f76daecd571269e79721',
    messagingSenderId: '234998723188',
    projectId: 'tangsugar-24bd1',
    databaseURL: 'https://tangsugar-24bd1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tangsugar-24bd1.appspot.com',
    iosBundleId: 'com.example.tangsugar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDq7npug1uu1odaLn92ZZnnYdIM3tVJ2c',
    appId: '1:234998723188:web:4cfb0dab562379ebe79721',
    messagingSenderId: '234998723188',
    projectId: 'tangsugar-24bd1',
    authDomain: 'tangsugar-24bd1.firebaseapp.com',
    databaseURL: 'https://tangsugar-24bd1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tangsugar-24bd1.appspot.com',
    measurementId: 'G-8XRRW4097D',
  );

}